name: Build and deploy docs

on:
  workflow_dispatch:
    inputs: &inputs
      ref:
        required: true
        type: string
        description: The tag or branch to deploy
      version:
        type: string
        description: The version to deploy
      git-branch:
        type: string
        description: Git branch to deploy to
        default: gh-pages
  workflow_call:
    inputs: *inputs

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Download source
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: Get ref SHA
        id: ref-sha
        run: |
          REF_SHA="$(git rev-parse --short HEAD)"
          echo "REF_SHA: ${REF_SHA}"
          echo "sha=${REF_SHA}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: shards install

      - name: Build docs
        run: |
          crystal docs \
            --project-version="${{ inputs.version || inputs.ref }}" \
            --source-refname="${{ steps.ref-sha.outputs.sha }}" \
            --json-config-url="/ameba/versions.json"

      - name: Deploy docs ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ${{ inputs.git-branch }}
          folder: docs
          target-folder: ${{ inputs.version || inputs.ref }}
          clean: true

  add-version-to-json-index:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    needs:
      - build-and-deploy

    steps:
      - name: Download source
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.git-branch }}

      - name: Update version list
        run: |
          VERSION="${{ inputs.version || inputs.ref }}"

          if [[ $VERSION =~ ^[0-9] ]]; then
            RELEASED="true"
          else
            RELEASED="false"
          fi

          JQ_EXPRESSION="
            .versions |= (
              if ( . | map(.name) | index(\"${VERSION}\") | not ) then
                . += [ {\"name\": \"${VERSION}\", \"url\": \"/ameba/${VERSION}/\", \"released\": ${RELEASED}} ]
              else
                .
              end
            )"

          cat versions.json | \
            jq "$JQ_EXPRESSION" > versions.json.tmp && \
            mv versions.json.tmp versions.json

      - name: Check for changes
        id: git-diff-changes
        run: |
          git diff --color

          if [[ -n "$(git diff --exit-code)" ]]; then
            echo "Changes detected."
            echo "has-changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected."
            echo "has-changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git identity
        if: steps.git-diff-changes.outputs.has-changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes to git
        if: steps.git-diff-changes.outputs.has-changes == 'true'
        run: |
          git commit -am "Update versions.json"
          git push -u origin HEAD
