name: "Upload Ameba SARIF"

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 3 * * 1" # Every monday at 3 AM

jobs:
  sarif:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        crystal: [latest, nightly]
    runs-on: ${{ matrix.os }}

    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Set timezone to UTC
        uses: szenius/set-timezone@v2.0

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}

      - name: Download source
        uses: actions/checkout@v6

      - name: Install dependencies
        run: shards install

      - name: Install typos-cli
        if: matrix.os == 'macos-latest'
        run: brew install typos-cli

      - name: Build ameba binary
        run: make build

      - name: Run Ameba with SARIF output
        run: make sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif.json
          category: ameba-${{ matrix.os }}-${{ matrix.crystal }}
