name: Update JSON Schema

on:
  push:
    branches: [master]
    paths:
      - "**/*.cr"

jobs:
  update-json-schema:
    runs-on: ubuntu-latest

    steps:
      - name: Set timezone to UTC
        uses: szenius/set-timezone@v2.0

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Create GitHub App token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.MASTER_PUSHER_APP_ID }}
          private-key: ${{ secrets.MASTER_PUSHER_PRIVATE_KEY }}

      - name: Download source
        uses: actions/checkout@v5
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Install dependencies
        run: shards install

      - name: Run JSON Schema builder
        run: shards run json-schema-builder

      - name: Check for changes
        id: git-diff-changes
        run: |
          if [[ -n "$(git diff --exit-code)" ]]; then
            echo "Changes detected."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git identity
        if: steps.git-diff-changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        if: steps.git-diff-changes.outputs.has_changes == 'true'
        run: |
          git commit -am "Update JSON Schema"
          git push -u origin HEAD
