name: Update rules reference

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - ".github/workflows/update-rules-reference.yml"
      - "shard.yml"
      - "**/*.cr"

permissions:
  contents: write

jobs:
  update-rules-reference:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Set timezone to UTC
        uses: szenius/set-timezone@v2.0

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Download source
        uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.MASTER_PUSHER_SSH_KEY }}

      - name: Install dependencies
        run: shards install

      - name: Run rules reference builder
        run: shards run rules-reference-builder

      - name: Check for changes
        id: git-diff-changes
        run: |
          if [[ -n "$(git diff --exit-code)" ]]; then
            echo "Changes detected."
            echo "has-changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected."
            echo "has-changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git identity
        if: steps.git-diff-changes.outputs.has-changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        if: steps.git-diff-changes.outputs.has-changes == 'true'
        run: |
          git commit -am "Update rules reference"
          git push -u origin HEAD
